### PR TITLE
Wip sunflower simclr modeling 18

### PR DESCRIPTION
**Pull request by jonathanvigil00**
## Description
- Implemented Simple contrastive learning of visualizations

## Features
- Wandb `sweeps.yml` 
- CLI argument parser
- config file to have default parameters
- Option to change backbone
- `model_run.py` to run a single run instead of sweeps
- `validate_model.py` script creates 2D and 3D visualizations using PCA, TSNE, and UMAP
- `plot_NxN_examples` function to create a grid based on distances 

## KNN plot of similarity search upon validation:
image
## 2D TSNE plot of embeddings with thumbnails:
image
## 3D Scatterplot of embeddings as gif:
3D_plot2

### CODE REVIEW

**Comment by nadia-eecs** [comment]
lgtm :thumbs up. Nice work on the visualizations :sunflower: s

**Comment by ReOp14** [comment]
Love it! Today we profit 💰💰💰🟩🟩🟩

**Review by ReOp14 — APPROVED** [review]
Love it! Today we profit 💰💰💰🟩🟩🟩

**Review by nadia-eecs — APPROVED** [review]
I really like the wandb sweeps with the option of using command line for `model_run.py`. Also the visualizations of the k-nearest neighbors with the distances is very useful for quantifying the similarity search effectiveness.
:+1: :sunflower: :sun_with_face: :bird: :unicorn: :cat2:

**Pull request merged**
